name: Build Skyrim LE Plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Baixar codigo-fonte
      uses: actions/checkout@v4

    - name: Configurar CMake (x86 / 32-bit para LE)
      run: cmake -B build -A Win32

    - name: Compilar a DLL
      run: cmake --build build --config Release

    - name: Disponibilizar DLL para Download
      uses: actions/upload-artifact@v4
      with:
        name: MCO_LE_Targeting_Fix_DLL
        path: build/Release/*.dll
